# Generated by Django 4.1.5 on 2023-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
