# Generated by Django 4.1.5 on 2023-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0003_column_created_at_column_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_range_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AddField(
            model_name='column',
            name='data_range_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='to'),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\t)'), (' ', 'Space ( )'), ('|', 'Vertical bar (|)')], default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=1),
        ),
    ]
