# Generated by Django 4.1.5 on 2023-01-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0004_column_data_range_from_column_data_range_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='column_name',
        ),
    ]
