# Generated by Django 4.1.5 on 2023-01-30 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0005_rename_name_column_column_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='files')),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_generator.dataschema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
