# Generated by Django 4.1.5 on 2023-01-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0007_generateddata_rows_generateddata_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddata',
            name='data_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_data', to='csv_generator.dataschema'),
        ),
    ]
